services:
  - type: web
    name: confluence-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_demo_users"
    startCommand: "gunicorn portal.wsgi:application --workers 2 --threads 4 --worker-class gthread --worker-tmp-dir /dev/shm --keep-alive 10 --timeout 120"
    healthCheckPath: /healthz/
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
