# Generated by Django 5.1.15 on 2026-09-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlog_facultyprofile_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen / Community'), ('student', 'Student'), ('faculty_mentor', 'Faculty Mentor'), ('university_coordinator', 'University Coordinator'), ('industry_partner', 'Industry Partner'), ('gov_admin', 'Government Admin'), ('admin', 'Super Admin / Master Admin')], default='citizen', max_length=30),
        ),
    ]
