# Generated by Django 5.1.15 on 2026-09-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auditlog_facultyprofile_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role_code", models.CharField(max_length=50)),
                ("is_staff", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Demo Credential",
                "verbose_name_plural": "Demo Credentials",
                "ordering": ["id"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("citizen", "Citizen / Community"),
                    ("student", "Student"),
                    ("faculty_mentor", "Faculty Mentor"),
                    ("university_coordinator", "University Coordinator"),
                    ("industry_partner", "Industry Partner"),
                    ("gov_admin", "Government Admin"),
                    ("admin", "Super Admin / Master Admin"),
                ],
                default="citizen",
                max_length=30,
            ),
        ),
    ]
