# Generated by Django 5.1.15 on 2026-09-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
        ('users', '0003_democredential_alter_user_role'),
    ]

    operations = [
    ]
